jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      env:
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      name: Build with Maven
      run: mvn verify -pl protocols -am --no-transfer-progress --batch-mode --fail-at-end
        -Denforcer.skip
    - continue-on-error: true
      if: ${{ always() }}
      name: Publish Test Report
      uses: ScaCap/action-surefire-report@v1.8.0
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
name: Integration Tests
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
